create table if not exists public.site_content (
  id bigint generated by default as identity primary key,
  section_key text not null unique,
  content jsonb not null,
  sort_order int not null default 0,
  updated_at timestamptz not null default now()
);

alter table public.site_content enable row level security;

drop policy if exists "Public content is readable" on public.site_content;
create policy "Public content is readable"
on public.site_content
for select
to anon
using (true);

insert into public.site_content (section_key, sort_order, content) values
('nav', 10, '["Home","Pages","SportsPress","Events","Blog","Shop"]'),
('hero', 20, '{
  "title": "Detailed basketball games news & reviews",
  "text": "Consectetur adipiscing elit, sed do eiusmod tempor incididunt dolore magna aliqua.",
  "button": "Read more",
  "background": "https://images.unsplash.com/photo-1546519638-68e109498ffc?q=80&w=1920",
  "eventDate": "2026-11-21T10:23:01Z"
}'),
('matches', 30, '[
  {
    "date": "Oct 16, 2024",
    "score": "129 - 112",
    "league": "Premier League",
    "venue": "Houston",
    "teams": ["Jazz","Celtics"],
    "logos": [
      "https://tornados.ancorathemes.com/wp-content/uploads/2024/12/team8-copyright.png",
      "https://tornados.ancorathemes.com/wp-content/uploads/2024/12/team4-copyright.png"
    ]
  },
  {
    "date": "Sep 29, 2024",
    "score": "127 - 120",
    "league": "Premier League",
    "venue": "Cleveland",
    "teams": ["Lakers","Pistons"],
    "logos": [
      "https://tornados.ancorathemes.com/wp-content/uploads/2024/12/team2-copyright.png",
      "https://tornados.ancorathemes.com/wp-content/uploads/2024/12/team7-copyright.png"
    ]
  },
  {
    "date": "Sep 14, 2024",
    "score": "119 - 102",
    "league": "Premier League",
    "venue": "Pittsburgh",
    "teams": ["Chicago Bulls","Miami Heat"],
    "logos": [
      "https://tornados.ancorathemes.com/wp-content/uploads/2024/12/team3-copyright.png",
      "https://tornados.ancorathemes.com/wp-content/uploads/2024/12/team6-copyright.png"
    ]
  }
]'),
('standings', 40, '[
  ["1","Jazz","3","2","1","4","https://tornados.ancorathemes.com/wp-content/uploads/2024/12/team8-copyright.png"],
  ["2","Pistons","3","2","1","4","https://tornados.ancorathemes.com/wp-content/uploads/2024/12/team7-copyright.png"],
  ["3","Chicago Bulls","2","2","0","4","https://tornados.ancorathemes.com/wp-content/uploads/2024/12/team3-copyright.png"],
  ["4","MAGIC BBC","2","1","1","2","https://tornados.ancorathemes.com/wp-content/uploads/2024/12/team1-copyright.png"],
  ["5","Lakers","2","1","1","2","https://tornados.ancorathemes.com/wp-content/uploads/2024/12/team2-copyright.png"],
  ["6","Mavericks","1","1","0","2","https://tornados.ancorathemes.com/wp-content/uploads/2024/12/team5-copyright.png"],
  ["7","Rockets","1","1","0","2","https://tornados.ancorathemes.com/wp-content/uploads/2024/12/team10-copyright.png"]
]'),
('featuredPosts', 50, '[
  {
    "category": "Stars",
    "date": "31 Oct",
    "title": "The greatest moments in basketball championship history",
    "excerpt": "Proin faucibus nec mauris a sodales, sed elementum mi tincidunt. Sed eget viverra egestas nisi in consequat.",
    "image": "https://tornados.ancorathemes.com/wp-content/uploads/2024/12/post32-copyright-840x574.jpg"
  },
  {
    "category": "Stars",
    "date": "30 Oct",
    "title": "Behind the glamour of basketball championship events",
    "excerpt": "Proin faucibus nec mauris a sodales, sed elementum mi tincidunt. Sed eget viverra egestas nisi in consequat.",
    "image": "https://tornados.ancorathemes.com/wp-content/uploads/2024/12/post33-copyright-840x574.jpg"
  }
]'),
('news', 60, '[
  ["The desire to make it to the semifinals 2025","https://tornados.ancorathemes.com/wp-content/uploads/2024/12/post34-copyright-890x664.jpg"],
  ["How teams prepare for basketball championships","https://tornados.ancorathemes.com/wp-content/uploads/2024/12/post35-copyright-890x664.jpg"],
  ["Strategies that win basketball championships","https://tornados.ancorathemes.com/wp-content/uploads/2024/12/post36-copyright-890x664.jpg"],
  ["Top records held in basketball championships","https://tornados.ancorathemes.com/wp-content/uploads/2024/12/post37-copyright-890x664.jpg"],
  ["Scores that make games really memorable","https://tornados.ancorathemes.com/wp-content/uploads/2024/12/post38-copyright-890x664.jpg"],
  ["The rise of underdogs in basketball championships","https://tornados.ancorathemes.com/wp-content/uploads/2024/12/post39-copyright-890x664.jpg"]
]'),
('portfolio', 70, '[
  ["The game","https://tornados.ancorathemes.com/wp-content/uploads/2020/05/post59-copyright-1.jpg"],
  ["The captain","https://tornados.ancorathemes.com/wp-content/uploads/2020/05/post60-copyright-1-890x664.jpg"],
  ["The training","https://tornados.ancorathemes.com/wp-content/uploads/2020/05/post61-copyright-1-890x664.jpg"],
  ["The score","https://tornados.ancorathemes.com/wp-content/uploads/2020/05/post62-copyright.jpg"]
]'),
('partners', 80, '[
  "https://tornados.ancorathemes.com/wp-content/uploads/2023/09/dark-partners-1-copyright.png",
  "https://tornados.ancorathemes.com/wp-content/uploads/2023/09/dark-partners-2-copyright.png",
  "https://tornados.ancorathemes.com/wp-content/uploads/2023/09/dark-partners-3-copyright.png",
  "https://tornados.ancorathemes.com/wp-content/uploads/2023/09/dark-partners-4-copyright.png",
  "https://tornados.ancorathemes.com/wp-content/uploads/2023/09/dark-partners-5-copyright.png",
  "https://tornados.ancorathemes.com/wp-content/uploads/2023/09/dark-partners-6-copyright.png"
]')
on conflict (section_key) do update set
  content = excluded.content,
  sort_order = excluded.sort_order,
  updated_at = now();
